# SPDX-License-Identifier: MIT
# Copyright (c) 2020 Gennady Trafimenkov

---

- name: Enable https transport
  apt: name=apt-transport-https state=present update_cache=true cache_valid_time=3600
  become: yes

- name: Add node gpg key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
  when: skip_node_deb_key_install|default(false) == false
  become: yes

- name: Add apt repository
  apt_repository: repo="deb https://deb.nodesource.com/node_12.x {{ansible_distribution_release}} main" state=present
  register: add_repo_result
  become: yes

- name: Update apt cache
  apt: update_cache=yes
  when: add_repo_result.changed == true
  become: yes

- name: Install nodejs
  apt: name=nodejs state=present
  become: yes
