# SPDX-License-Identifier: MIT
# Copyright (c) 2020 Gennady Trafimenkov
---
- hosts:
    - app01
    - mon01

  tasks:
    - name: Setup node exporter
      apt:
        name: prometheus-node-exporter-collectors
        update_cache: true
        cache_valid_time: 3600
      become: yes
