# SPDX-License-Identifier: MIT
# Copyright (c) 2020 Gennady Trafimenkov

# List of packages required to install ruby, split by distribution name.
dependency_packages:
  ubuntu:
    - autoconf
    - automake
    - bison
    - g++
    - gcc
    - libc6-dev
    - libffi-dev
    - libgdbm-dev
    - libgmp-dev
    - libncurses5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libtool
    - libyaml-dev
    - make
    - pkg-config
    - sqlite3
    - zlib1g-dev
