# SPDX-License-Identifier: MIT
# Copyright (c) 2020 Gennady Trafimenkov
---

- name: Enable https transport
  apt: name=apt-transport-https state=present update_cache=true cache_valid_time=3600
  become: yes

- name: Add repository gpg key
  apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg state=present
  when: skip_node_deb_key_install|default(false) == false
  become: yes

- name: Add apt repository
  apt_repository: repo="deb https://dl.yarnpkg.com/debian/ stable main" state=present
  register: add_repo_result
  become: yes

- name: Update apt cache
  apt: update_cache=yes
  when: add_repo_result.changed == true
  become: yes

- name: Install yarn package
  apt: name=yarn state=present
  become: yes
