# SPDX-License-Identifier: MIT
# Copyright (c) 2020 Gennady Trafimenkov

global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - '10.116.101.11:9100'
          - '10.116.101.12:9100'

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
